FROM mcr.microsoft.com/devcontainers/base:jammy
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get install -y firefox-esr
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get install -y firefox
